# BM6 Battery Monitor - tested on ESPHome 2024.8.0
# Heavily borrowed code from: https://github.com/KrystianD/bm2-battery-monitor

esphome:
  includes:
    - "bm6.h"

esp32:
  board: esp32dev
  framework:
    type: arduino

##################################################################
# Add your ESPHome config above this line                        #
# Make sure to keep the bm6.h include line under esphome section #
# Also update the mac_address and interval lines below           #
##################################################################

esp32_ble_tracker:
  scan_parameters:
    continuous: false
    duration: 5s

ble_client:
  - id: bm6
    mac_address: 00:00:00:00:00:00 # Put your BM6 address here

interval:
  - interval: 30min # How often you want to poll the BM6
    then:
      - esp32_ble_tracker.start_scan:
      - delay: 5s
      - esp32_ble_tracker.stop_scan:

sensor:
  - platform: batterymonitor_bm6
    id: bm_bm6
    encryption_key: [ 108, 101, 97, 103, 101, 110, 100, 255, 254, 48, 49, 48, 48, 48, 48, 57 ]
    ble_client_id: bm6
    update_interval: 30min
    temperature:
      name: "Battery temperature"
    battery_voltage:
      name: "Battery voltage"
    battery_level:
      name: "Battery level"
